### ISSUE TITLE
Can only run memeoff if within the same directory as run_discord.py

### ISSUE THREAD

**Issue by r3w0p** [r3w0p/memeoff#2]
### Description

When trying to run run_discord.py outside of the memeoff directory in which it is situated, PIL fails to load the necessary fonts from `config`.

I.e. when running...

`/path/to/venv/bin/python3 /path/to/run_discord.py -token <token>`

...instead of...

`./venv/bin/python3 ./run_discord.py -token <token>`

### Traceback

`Traceback (most recent call last):
  File "/path/to/run_discord.py", line 6, in <module>
    from meme import *
  File "/path/to/meme.py", line 6, in <module>
    FONT_ARIMO = ImageFont.truetype(FONT_ARIMO_PATH, 36)
  File "/path/to/venv/lib/python3.7/site-packages/PIL/ImageFont.py", line 852, in truetype
    return freetype(font)
  File "/path/to/venv/lib/python3.7/site-packages/PIL/ImageFont.py", line 849, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/path/to/venv/lib/python3.7/site-packages/PIL/ImageFont.py", line 210, in __init__
    font, size, index, encoding, layout_engine=layout_engine
OSError: cannot open resource`

### Setup

 - OS: Raspberry Pi OS
 - Version: Source

**Comment by r3w0p** [comment]
Fixed by using `Path(__file__).parent.absolute()` to get the current file's absolute path regardless of where it is called at command line.
